// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {id: 0, name: 'Josimar Henrique da Silva', photo: 'assets/persona1.png', depoiment: '“Há mais de 10 anos sou cliente da Renee Trajar. A qualidade, caimento e possibilidade de customização das roupas, aliados ao excelente atendimento e prazo de entrega são fatores decisivos para mim.”', description: 'Diretor Presidente | Grupo Hebron', active: true},
  {id: 1, name: 'William H. M. Garey', photo: 'assets/persona4.png', depoiment: '“Sou cliente do Renee há uns 12 anos. Nosso primeiro contato foi por intermédio de meu pai, que já têm uma história de décadas com o querido Renee. O excelente atendimento antes e pós venda e a alta qualidade dos materiais usados colocam a Renee Trajar em um patamar acima dos demais do ramo.”', description: 'Advogado | Nelson Garey Advogados Associados', active: false},
  {id: 2, name: 'Domingos Orestes Chiomento', photo: 'assets/persona3.png', depoiment: '“Seu corte tanto de camisas, bem como de ternos são impecáveis, muitos dos meus amigos tem elogiado a vestimenta. Recomendo para quem gosta de perfeição. Estamos nos servindo do trabalho do Renee Trajar há mais de vinte anos.”', description: 'DOC Contabilidade Empresarial', active: false},
  {id: 3, name: 'José Mauro Marques', photo: 'assets/persona5.png', depoiment: '“Tenho a honra de afirmar que enquanto nossas vidas perdurarem o meu conceito é sempre melhor em relação ao Renee Trajar, sua pessoa, ao profissional competente e idôneo, sempre pontual, atencioso e preocupado em atender da melhor maneira os anseios de seus clientes, incluindo este signatário.”', description: 'Advogado', active: false},
  {id: 4, name: 'Custódio Pereira', photo: 'assets/persona6.png', depoiment: '“Conheço o excelente e qualificado trabalho do Renee Trajar e sua equipe há décadas. Para camisas e ternos, o Renee é imbatível, sempre com preços justos, produtos de excelente qualidade e especialmente tudo é feito com muito cuidado e qualidade. Cumpre os prazos com atendimento de alto nível. O Renee trabalha com perfeição nos detalhes.”', description: 'Membro do CONSOCIAL - Conselho Superior de Responsabilidade Social da FIESP-SP', active: false}
]

